<html>
<body>
<h1>Paginator Demo 1</h1>
<?php if (count($this->paginator)): ?>
<ul>
<?php foreach ($this->paginator as $item): ?>
  <li><?php echo var_export($item,1); ?></li>
<?php endforeach; ?>
</ul>
<?php endif; ?>

<?php echo $this->paginationControl($this->paginator,
                                    'Sliding',
                                    'index/my_pagination_control.phtml'); ?>
<hr/>
<a href="<?=$this->url(array('action'=>'index')); ?>">index page</a>
</body>
</html>
